package com.h.fileinput.db.greenDao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.h.fileinput.db.greenBean.CookBean;

import com.h.fileinput.db.greenDao.CookBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cookBeanDaoConfig;

    private final CookBeanDao cookBeanDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cookBeanDaoConfig = daoConfigMap.get(CookBeanDao.class).clone();
        cookBeanDaoConfig.initIdentityScope(type);

        cookBeanDao = new CookBeanDao(cookBeanDaoConfig, this);

        registerDao(CookBean.class, cookBeanDao);
    }
    
    public void clear() {
        cookBeanDaoConfig.getIdentityScope().clear();
    }

    public CookBeanDao getCookBeanDao() {
        return cookBeanDao;
    }

}
