package com.h.fileinput.db.greenBean;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "COOK_BEAN".
 */
public class CookBean {

    private Long id;
    private String title;
    private String url;
    private String imgPath;
    private String createUser;
    private String userUrl;
    private String cateName;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public CookBean() {
    }

    public CookBean(Long id) {
        this.id = id;
    }

    public CookBean(Long id, String title, String url, String imgPath, String createUser, String userUrl, String cateName) {
        this.id = id;
        this.title = title;
        this.url = url;
        this.imgPath = imgPath;
        this.createUser = createUser;
        this.userUrl = userUrl;
        this.cateName = cateName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getImgPath() {
        return imgPath;
    }

    public void setImgPath(String imgPath) {
        this.imgPath = imgPath;
    }

    public String getCreateUser() {
        return createUser;
    }

    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    public String getUserUrl() {
        return userUrl;
    }

    public void setUserUrl(String userUrl) {
        this.userUrl = userUrl;
    }

    public String getCateName() {
        return cateName;
    }

    public void setCateName(String cateName) {
        this.cateName = cateName;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
